Fixing installer, and write_log function

diff --git a/bin/ucb b/bin/ucb
--- a/bin/ucb
+++ b/bin/ucb
@@ -61,8 +61,12 @@ function write_log {
    
   # if log file doesn't exist, we create it
   if [ ! -f ${UCB_LOG_FILE} ]; then
-    write_log "Not exist the log file ${UCB_LOG_FILE}, creating it !!!"
     touch ${UCB_LOG_FILE}
+    if [ $? -ne ${TRUE} ]; then
+     echo "Can't create log file ${UCB_LOG_FILE}"
+     exit 1
+    fi
+    echo "${DATE_LOG}: Not exist the log file ${UCB_LOG_FILE}, creating it !!!" >> ${UCB_LOG_FILE}
   fi
 
   DATE_LOG=$(date "+%Y-%m-%d %H:%M:%S")
